### ISSUE TITLE
Similarities to LLaVA-HR

### ISSUE THREAD

**Issue by luogen1996** [dvlab-research/MiniGemini#15]
Congratulations on your great work and solid performance! However, we notice that your core idea and design are highly similar to our previsiou work [ LLaVA-HR](https://arxiv.org/abs/2403.03003), especially the dual visual pathways for MLLMs.   We would like to see simple clarifications and  discussions with our work in your paper. Thank you!

**Comment by yanwei-li** [comment]
Hi, thanks for your interest in our work and also congrats to your great work!
But we do not think the comparisons are essential at this version, there are two reasons.
1. We don’t think the core idea and design are highly similar to your work. In Mini-Gemini, HR is used to provide candidates only and used to provide the key and value, which is quite different from your work. Dual pathways is widely-used things in CV, so we donot view it neither  declare it as a total novelty in our work. Moreover, HR is only one point in Mini-Gemini.
2. We view these two works as concurrent work, and the released date only has about two weeks. Because LLaVA-HR is released at 03/05, and we already finished all validation experiments and also start the method writing at that time. So, we don’t view it as the previous work and not include it for discussion.
Of course, in the future work or next version, we will compare with your work with further discussion.

**Comment by luogen1996** [comment]
Thank you! We sincerely wish you good luck !
