### ISSUE TITLE
Demo inference wrong?

### ISSUE THREAD

**Issue by lucasjinreal** [dvlab-research/MiniGemini#3]
![image](https://github.com/dvlab-research/MiniGemini/assets/21303438/998819b5-26fa-44a2-9e58-815a57af603b)

Don't see any positive information on a simple task?

**Comment by yanwei-li** [comment]
Sorry for this confusion. It is caused by the OCR function in this demo, which is not used for normal inference with too many characters. Please close the OCR assistant here and try again
<img width="457" alt="截屏2024-03-28 15 38 41" src="https://github.com/dvlab-research/MiniGemini/assets/24286910/2e0a5c2f-e151-4b8b-9599-12c649e951eb">

We try a similar case and get the results like this:
![WechatIMG5030](https://github.com/dvlab-research/MiniGemini/assets/24286910/93b359d5-bfaf-43f4-bf34-aa7662ab6b2a)

**Comment by lucasjinreal** [comment]
thanku,  may I ask why vision encoders all not tuned in these family?

**Comment by yanwei-li** [comment]
Hi, there are two reasons:
1. We found optimizing vision encoders did bring a performance increase, but not significant enough.
2. Considering the extra cost brought by the optimization process and limited resources for large models, we decided not to optimize it.
